name: Deploy Jekyll site to GitHub Pages
on:
  push:
    branches:
      - master  # 将此替换为您的主要分支名称，如 gh-pages、master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - name: Build and Deploy
        uses: helaili/jekyll-action@2.4.0
        with:
          # Use the access token GitHub automatically provides to action
          deploy-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # The folder where the website is built
          working-directory: ./_site
          # GitHub Pages options
          commit-message: ${{ github.event.head_commit.message }}
          committer-name: ${{ github.event.head_commit.author.name }}
          committer-email: ${{ github.event.head_commit.author.email }}
